services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=2224
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  discovery-reserva:
    build: './discovery-reserva'
    container_name: discovery-reserva
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - mysql
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 5000'

  gateway:
    build: './gateway'
    container_name: gateway
    restart: always
    ports:
      - "5051:5051"
    depends_on:
      - mysql
      - discovery-reserva
    networks:
      - app-network

  cadastro_hotel:
    build: './cadastro_hotel'
    container_name: cadastro_hotel
    restart: always
    ports:
      - "8080:5051"
    depends_on:
      - mysql
      - discovery-reserva
      - gateway
    networks:
      - app-network

  reserva:
    build: './reserva'
    container_name: reserva
    restart: always
    ports:
      - "6060:5051"
    depends_on:
      - mysql
      - discovery-reserva
      - gateway
      - cadastro_hotel
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
