CREATE TABLE TB_RESERVA (
    ID_RESERVA BIGINT AUTO_INCREMENT PRIMARY KEY,
    NM_HOTEL VARCHAR(255) NOT NULL,
    NM_HOSPEDE VARCHAR(255) NOT NULL,
    DT_CHECK_IN VARCHAR(255) NOT NULL,
    DT_CHECK_OUT VARCHAR(255) NOT NULL,
    NRO_QUARTO INT,
    STATUS_RESERVA VARCHAR(50),
);
