services:
  reserva:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    volumes:
      - ./tmp:/tmp
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_reserva?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2224

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 2224
      MYSQL_DATABASE: db_reserva
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
