services:
  cadastro-hotel:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./tmp:/tmp
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_cadastro_hotel?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=2224

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 2224
      MYSQL_DATABASE: db_cadastro_hotel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
